# Generated by Django 5.1.6 on 2025-02-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='funding_status',
            field=models.CharField(choices=[('not_funded', 'Not Funded'), ('partially_funded', 'Partially Funded'), ('fully_funded', 'Fully Funded')], default='not_funded', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='responsible_section',
            field=models.CharField(choices=[('medical', 'Medical Support Program'), ('humanitarian', 'Humanitarian Aid Program')], default='medical', max_length=50),
        ),
    ]
