# Generated by Django 5.1.6 on 2025-02-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the case is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark this case as urgent'),
        ),
        migrations.AddField(
            model_name='case',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target date for completing the fundraising', null=True),
        ),
    ]
